name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-cleanup: never
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle changed modules only
        shell: bash
        run: ./gradlew "module" --no-daemon --stacktrace --build-cache -I gradle/cache-retention.init.gradle